version: "3.0"

services:
  gateway:
    image: kong/kong-gateway
    restart: always
    ports:
      - 8001:8001
      - 8002:8002
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=db
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=postgres
      - KONG_PG_PASSWORD=postgres
      - KONG_ADMIN_LISTEN=0.0.0.0:8001,0.0.0.0:8444 ssl
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=kong
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  init-db:
    image: kong/kong-gateway
    command: >
      bash -c
      "for i in `seq 1 30`; do
        echo trying $$i...
        sleep 5
        kong migrations bootstrap 2>&1 && echo \"Success\" && break
      done; (exit 0)"
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=db
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=postgres
      - KONG_PG_PASSWORD=postgres
      - KONG_ADMIN_LISTEN=0.0.0.0:8001,0.0.0.0:8444 ssl
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
    depends_on:
      - db

  #konga:
  #  image: pantsel/konga
  #  restart: always
  #  ports:
  #    - 1337:1337

